--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-09-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "DBP"."COMPANY" 
   (	"COMPANY_ID" VARCHAR2(20 BYTE), 
	"BUSINESS_NO" VARCHAR2(30 BYTE), 
	"COMPANY_NAME" VARCHAR2(100 BYTE), 
	"COMPANY_SIZE" VARCHAR2(50 BYTE), 
	"CREDIT_GRADE" VARCHAR2(10 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DBP.COMPANY
SET DEFINE OFF;
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000001','124-81-00998','삼성전자','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000002','101-81-09147','현대자동차','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000003','133-85-00011','기아','대기업','AA-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000004','426-81-00521','KB금융지주','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000005','126-81-03725','SK하이닉스','대기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000006','301-87-02315','포스코','대기업','A+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000007','211-86-97088','신한금융지주','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000008','107-81-98139','LG화학','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000009','107-86-71509','하나금융지주','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000010','101-81-16406','현대모비스','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000011','202-81-45975','삼성물산','대기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000012','104-81-26688','삼성생명','대기업','A+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000013','124-81-31282','삼성SDI','대기업','A-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000014','783-85-00169','SK','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000015','101-82-03970','산업은행','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000016','202-81-16825','한화','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000017','101-86-32319','SK이노베이션','대기업','BBB-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000018','120-82-00557','한국가스공사','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000019','539-86-00614','HD현대','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000020','107-86-14075','LG전자','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000021','120-82-00052','한국전력','대기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000022','202-81-45617','삼성화재','대기업','AA+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000023','202-81-46197','HMM','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000024','102-81-42945','KT','대기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000025','220-88-14824','메리츠금융지주','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000026','201-81-45593','DB손해보험','대기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000027','206-86-50913','이마트','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000028','116-81-36743','S-Oil','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000029','110-81-14794','대한항공','대기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000030','104-81-26714','CJ','대기업','A-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000031','121-81-10385','현대제철','대기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000032','220-81-62517','네이버','대기업','AAA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000033','211-81-08071','(주)정원엔시스','중견기업','BBB+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000034','120-81-86581','(주)에스엘라이팅','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000035','120-81-08227','(주)모나미','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000036','513-81-16496','아주스틸(주)','중견기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000037','203-81-51830','한일단조공업(주)','중견기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000038','513-81-08939','성안합섬(주)','중견기업','BB+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000039','620-81-01350','엔브이에이치코리아(주)','중견기업','B');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000040','317-81-19217','(주)우진산전','중견기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000041','131-81-95829','(주)에이스테크놀로지','중견기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000042','603-81-15335','(주)동화엔텍','중견기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000043','699-81-00454','(주)신영','중견기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000044','301-81-05474','자화전자(주)','중견기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000045','124-81-05047','대원전선(주)','중견기업','BB+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000046','615-81-08287','비에이치아이(주)','중견기업','B');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000047','513-81-18418','(주)화인알텍','중견기업','BBB-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000048','220-81-03987','(주)해안종합건축사사무소','중견기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000049','609-81-01805','퍼스텍(주)','중견기업','B+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000050','129-81-16613','(주)다산네트웍스','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000051','124-81-32942','이화다이아몬드공업(주)','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000052','202-81-47522','동국산업(주)','중견기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000053','825-86-00441','대원스틸(주)','중견기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000054','113-81-08840','애경화학(주)','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000055','104-81-34422','계양전기(주)','중견기업','A-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000056','621-81-05271','(주)한금','중견기업','A+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000057','513-81-07376','(주)탑엔지니어링','중견기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000058','613-81-34310','(주)디티알','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000059','214-81-15867','(주)희림종합건축사무소','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000060','134-81-08473','(주)더존비즈온','중견기업','B-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000061','417-81-04580','(주)성창이엔씨','중견기업','BB-');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000062','135-81-19745','(주)루멘스','중견기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000063','863-87-00270','(주)휴온스','중견기업','BB+');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000064','129-81-21998','(주)켐트로닉스','중견기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000065','220-81-01733','(주)다우데이타','중견기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000066','214-81-83536','(주)안랩','중견기업','AA');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000067','133-81-22322','(주)대화제약','중견기업','B');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000068','105-86-12052','(주)다림엔지니어링','중소기업','CCC');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000069','642-87-00732','(유)옥경','중소기업','CC');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000070','221-82-07135','동화푸드','중소기업','C');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000071','401-81-15568','(주)대한이앤아이','중소기업','B');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000072','141-02-86375','이채이앤씨','중소기업','CC');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000073','120-86-47021','삼일건설산업','중소기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000074','206-31-61292','태산약품','중소기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000075','120-87-92182','(주)지맥','중소기업','CC');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000076','261-81-28112','고려산업','중소기업','CCC');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000077','503-86-07092','(주)나경','중소기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000078','457-81-02969','모비텍','중소기업','A');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000079','135-81-68741','(주)엠제이케이','중소기업','BB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000080','201-81-02823','(주)한진','중소기업','B');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000081','845-87-00160','(주)세진정공','중소기업','BBB');
Insert into DBP.COMPANY (COMPANY_ID,BUSINESS_NO,COMPANY_NAME,COMPANY_SIZE,CREDIT_GRADE) values ('COM-000082','110-81-34859 ','(주)밀알제이앤피','중소기업','B');
--------------------------------------------------------
--  DDL for Index SYS_C008414
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBP"."SYS_C008414" ON "DBP"."COMPANY" ("COMPANY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger COMPANY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DBP"."COMPANY_TRG" 
BEFORE INSERT ON Company
FOR EACH ROW
BEGIN
    :NEW.company_id := 'COM-' || LPAD(Company_SEQ.NEXTVAL, 6, '0');
END;
/
ALTER TRIGGER "DBP"."COMPANY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "DBP"."COMPANY" MODIFY ("BUSINESS_NO" NOT NULL ENABLE);
  ALTER TABLE "DBP"."COMPANY" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "DBP"."COMPANY" ADD PRIMARY KEY ("COMPANY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
